---
name: Feature request
about: Suggest an idea
title: "[FEATURE] "
labels: enhancement
assignees: ""
---

## Problem

What problem are you trying to solve?

## Proposed Solution

Describe your idea.

## Alternatives Considered

Any alternative solutions?

## Additional Context

Extra information.
