name: Terraform

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [main]
    paths:
      - 'infra/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:

env:
  TF_VERSION: "1.9.0"
  AWS_REGION: "eu-north-1"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  terraform-dev:
    name: Terraform Dev
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/envs/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -no-color
