name: Terraform Prod

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action to run"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

env:
  TF_VERSION: "1.9.0"
  AWS_REGION: "eu-north-1"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  terraform-prod:
    name: Terraform Prod (${{ github.event.inputs.action }})
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/envs/prod

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -no-color
